//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushPull
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prueba
    {
        public int ID { get; set; }
        public string RNC { get; set; }
        public string Periodo { get; set; }
        public string Codigo_nomina { get; set; }
        public string Documento_tipo { get; set; }
        public string Documento { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Apellido2 { get; set; }
        public Nullable<int> Salario { get; set; }
        public Nullable<int> Aporte { get; set; }
    }
}
